name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Build
        run: |
          bun run build
          bun run build:firefox

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: .output/*.zip
